config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }


  resources :games do
    resources :screenshots, only: [:create, :show, :destroy, :index]
    resources :comments
  end

  resources :users, only: [:show]

  get '/completed_games', to: 'users#user_completed'
  get '/user_screenshots', to: 'users#screenshots'
  root 'library#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :rating, presence: true

  belongs_to :user
  has_many :screenshots
  has_many :comments



  def screenshots_attributes=(screenshot_attributes)
    screenshot_attributes.each do |i, attributes|
      self.screenshots.build(attributes)
    end
  end

  def self.completed_games
    self.all.collect{|game| game if game.completed}
  end

end

app/models/screenshot.rb
class Screenshot < ApplicationRecord
  has_attached_file :picture, styles: {medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
  belongs_to :game


  def avatar_url
    picture.url
  end


  def med_url
    picture.url(:medium)
  end
  # def self.previous(screenshot)
  #   where('id > ?', screenshot.id).first
  # end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :games
  has_many :screenshots, through: :games
  validates :username, presence: :true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      binding.pry
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.username = auth.info.nickname
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @game = Game.find(params[:game_id])
    @comments = @game.comments
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @comments.to_json}
    end
  end

  def create
    @game = Game.find(params[:game_id])
    @comment = @game.comments.build(comments_params)
    if @comment.save
      respond_to do |format|
        format.html {render :show, :layout => false}
        format.json {render json: @comment.to_json}
      end
    end
  end

  private

  def comments_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]

  def index
    @games = Game.all
  end

  def new
    @game = Game.new
    @screenshot = @game.screenshots.build
  end

  def create
    @game = current_user.games.build(game_params)
    if @game.save
      flash[:notice] = "Game successfully created!"
      redirect_to user_path(current_user)
    else
      flash[:alert] = "Game not saved."
      render :new
    end
  end

  def show
    @game = Game.find(params[:id])
    @screenshot = @game.screenshots.build
    @comment = @game.comments.build
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @game.to_json}
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    if @game.update(game_params)
      flash[:notice] = "Game successfully updated."
      redirect_to user_path(current_user)
    else
      flash[:alert] = "Game not updated."
      render :edit
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    flash[:notice] = "Game successfully deleted"
    redirect_to user_path(current_user)
  end

  private

  def game_params
    params.require(:game).permit(:title, :description, :rating, :completed, :notes, :screenshots_attributes =>[:caption, :picture])
  end
end

app/controllers/library_controller.rb
class LibraryController < ApplicationController
  def index
    
  end
end

app/controllers/screenshots_controller.rb
class ScreenshotsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]


  def create
    @game = Game.find(params[:game_id])
    @screenshot = @game.screenshots.build(screenshots_params)
    if @screenshot.save
      flash[:notice] = "Sreenshot saved!"
      redirect_to game_path(@game)
    else
      flash[:alert] = "Screenshot not saved."
      redirect_to game_path(@game)
    end
  end

  def index
    game = Game.find(params[:game_id])
    @screenshots = game.screenshots
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @screenshots.to_json(:methods => :avatar_url)}
    end
  end

  def show
    @screenshot = Screenshot.find(params[:id])
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @screenshot.to_json}
    end
  end

  def destroy
    @screenshot = Screenshot.find(params[:id])
    @game = Game.find(params[:game_id])
    @screenshot.destroy
    flash[:notice] = "Screenshot successfully deleted"
    redirect_to game_path(@game)
  end

  private

  def screenshots_params
    params.require(:screenshot).permit(:caption, :picture)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def user_completed
    @games = current_user.games.completed_games
  end

  def screenshots
    @screenshots = current_user.screenshots
    respond_to do |format|
      format.html {render :screenshots}
      format.json {render json: @screenshots.to_json(:methods => [:avatar_url, :med_url, :game])}
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
  return '' if resource.errors.empty?

   messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
   sentence = I18n.t('errors.messages.not_saved',
   count: resource.errors.count,
   resource: resource.class.model_name.human.downcase)

   html = <<-HTML

   <div class="alert alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
    <h4>Unsuccessful</h4>
    #{messages}
   </div>
   HTML

   html.html_safe
 end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/helpers/screenshots_helper.rb
module ScreenshotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<% @comments.each do |comment| %>
  <%= comment.content %>
<% end %>

app/views/comments/show.html.erb
<li class='col-12 comment-box'><%= @comment.content %></li>

app/views/games/_complete.html.erb
<% if game.completed %>
  <h3>Game Completed!</h3>
  <p><i class="fa fa-check-square-o" aria-hidden="true"></i></p>
<% else %>
  <h3>Game Not Completed</h3>
  <p><i class="fa fa-square-o" aria-hidden="true"></i></p>
<% end %>

app/views/games/_form.html.erb
<% if @game.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @game.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end%>
<div class="game-form">

  <h1 class= "text-center">Add a New Game</h1><br>

  <%= form_for @game do |f| %>
    <div class="field row">
      <%= f.label :title, class: "h4 col-2 col-form-label"%>
      <%= f.text_field :title, class: "col-10 form-control" %>
    </div>
    <br>

    <div class="field row">
      <%= f.label :description, "Brief description of the game:" %> <br>
      <%= f.text_area :description, class: "form-control col-12" %>
    </div>
    <br>

    <div class="field row">
      <%= f.label :notes, "Player Notes:" %> <br>
      <%= f.text_area :notes, class: "form-control col-12" %>
    </div>
    <br>

    <%= f.fields_for :screenshots do |screenshot_builder| %>
      <div class="field row">
        <%= screenshot_builder.label :picture, "Upload Screenshot:", class: "col-4 h5 col-form-label" %>
        <%= screenshot_builder.file_field :picture, class: "col-8 form-control" %>
      </div>
      <br>
      <div class=" field row">
        <%= screenshot_builder.label :caption, class: "col-4 h5 col-form-label" %>
        <%= screenshot_builder.text_field :caption, class: "col-8 form-control" %>
      </div>
    <% end %>

    <br>

    <div class="form-check form-check-inline col-12">
      Game Rating: &nbsp;
      <%= f.radio_button :rating, '1 Star' %>
      <%= f.label :rating, '1 Star', :value => '1 Star' %>&nbsp;
      <%= f.radio_button :rating, '2 Stars' %>
      <%= f.label :rating, '2 Stars', :value => '2 Stars' %>&nbsp;
      <%= f.radio_button :rating, '3 Stars' %>
      <%= f.label :rating, '3 Stars', :value => '3 Stars' %>&nbsp;
      <%= f.radio_button :rating, '4 Stars' %>
      <%= f.label :rating, '4 Stars', :value => '4 Stars' %>&nbsp;
      <%= f.radio_button :rating, '5 Stars' %>
      <%= f.label :rating, '5 Stars', :value => '5 Stars' %>
    </div>
    <br>

    <div class="field">
      <%= f.check_box :completed%> &nbsp;
      <%= label :completed, "Check box if game has been completed.", class: "col-form-label"%>
    </div>
    <br>

    <%= f.submit "Add Game", :class=> "btn btn-primary" %>

  <% end %>

</div>

app/views/games/_form_edit.html.erb
<div class="game-form">

  <h1 class= "text-center">Edit Game</h1><br>

  <%= form_for @game do |f| %>
    <div class="field row">
      <%= f.label :title, class: "h4 col-2 col-form-label"%>
      <%= f.text_field :title, class: "col-10 form-control" %>
    </div>
    <br>

    <div class="field row">
      <%= f.label :description, "Brief description of the game:" %> <br>
      <%= f.text_area :description, class: "form-control col-12" %>
    </div>
    <br>

    <div class="field row">
      <%= f.label :notes, "Player Notes:" %> <br>
      <%= f.text_area :notes, class: "form-control col-12" %>
    </div>

    <br>

    <div class="form-check form-check-inline col-12">
      Game Rating: &nbsp;
      <%= f.radio_button :rating, '1 Star' %>
      <%= f.label :rating, '1 Star', :value => '1 Star' %>&nbsp;
      <%= f.radio_button :rating, '2 Stars' %>
      <%= f.label :rating, '2 Stars', :value => '2 Stars' %>&nbsp;
      <%= f.radio_button :rating, '3 Stars' %>
      <%= f.label :rating, '3 Stars', :value => '3 Stars' %>&nbsp;
      <%= f.radio_button :rating, '4 Stars' %>
      <%= f.label :rating, '4 Stars', :value => '4 Stars' %>&nbsp;
      <%= f.radio_button :rating, '5 Stars' %>
      <%= f.label :rating, '5 Stars', :value => '5 Stars' %>
    </div>
    <br>

    <div class="field">
      <%= f.check_box :completed%> &nbsp;
      <%= label :completed, "Check box if game has been completed.", class: "col-form-label"%>
    </div>
    <br>

    <%= f.submit "Edit Game", :class=> "btn btn-primary" %>

  <% end %>

</div>

app/views/games/_screenshot_modal.html.erb
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  Add New Screenshot
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add Screenshot</h4>
      </div>
      <div class="modal-body">
        <%= form_for screenshot, url: game_screenshots_path(game) do |f| %>
          <div class="row">
            <%= f.label :picture, "Upload Screenshot:", class: "col-4 col-form-label" %>
            <%= f.file_field :picture, class: "col-7 form-control" %>
          </div>
          <br>
          <div class="row">
            <%= f.label :caption, class: "col-4 col-form-label" %>
            <%= f.text_field :caption, class: "col-7 form-control" %>
          </div>
      </div>
      <div class="modal-footer">
          <p class= "text-center"><%= f.submit "Add New Screenshot", class: "btn btn-primary"%></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/games/_screenshots.html.erb
  <div class="col-12 text-center">
    <h2 class= "game-title text-center">SCREENSHOTS</h2>
  </div>
  <% screenshots.each do |pic|%>
    <% unless pic.id.nil? %>
      <%= link_to game_screenshot_path(pic.game_id, pic) do %>
        <span id="<%= pic.id %>" class="this-pic"><%= image_tag pic.picture.url(:medium), class: "img-fluid" %></span>
      <% end %>
    <% end %>
  <% end %>

app/views/games/_stars.html.erb
<div class="text-center">
  <% if rating == "5 Stars"%>
    <%= rating %> <br>
    <i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i>
  <% elsif rating == "4 Stars" %>
    <%= rating %>
    <i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i>
  <% elsif rating == "3 Stars" %>
    <%= rating %>
    <i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i>
  <% elsif rating == "2 Stars" %>
    <%= rating %>
    <i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i>
  <% else %>
    <%= rating %>
    <i class="fa fa-star" aria-hidden="true"></i>
  <% end %>
</div>

app/views/games/create.html.erb
<h1>Games#create</h1>
<p>Find me in app/views/games/create.html.erb</p>

app/views/games/destroy.html.erb
<h1>Games#destroy</h1>
<p>Find me in app/views/games/destroy.html.erb</p>

app/views/games/edit.html.erb
<br>
<%= render 'games/form_edit' %>

app/views/games/index.html.erb
<h1>Games#index</h1>
<p>Find me in app/views/games/index.html.erb</p>

app/views/games/new.html.erb
<br>
<%= render 'games/form' %>

app/views/games/show.html.erb
<div class="container game-box">
  <h1 class= "game-title text-center"><%= @game.title.upcase %></h1>
  <p><%= @game.description %></p>
  <div class="row col-12">
    <div class="col-4 game-stats">
      <strong>Player Notes:</strong>
      <p><%= @game.notes %></p>
    </div>
    <div class="col-4 game-stats text-center">
      <strong>Game Rating:</strong> <br>
      <%= render partial: "games/stars", locals: {rating: @game.rating} %>
    </div>
    <div class="col-4 game-stats text-center">
      <%= render partial: "games/complete", locals: {game: @game} %>
    </div>
  </div>
  <div class="col-12 text-center">
    <%= link_to "Edit Game", edit_game_path(@game), class: "col-2 btn btn-info"  %>
    <%= link_to 'Delete Game', game_path(@game), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger col-2' %>
  </div>
</div>
<div class="container game-box text-center" id="game-screenshots">
  <%= render partial: "games/screenshots", locals: {screenshots: @game.screenshots} %>
  <div class="col-12 text-center">
    <br>
    <%= render partial: "games/screenshot_modal", locals: {screenshot: @screenshot, game: @game} %>
  </div>
</div>

<div class="container game-box" id="game-comments" data-game="<%= @game.id %>">
  <h2 class= "game-title text-center">GAME NOTES</h2>
  <ul id="comment-box">

  </ul>

  <div class="comment-form">

    <%= form_for @comment, url: game_comments_path(@game) do |f| %>
      <div class="field row">
        <%= f.label "Notes:", class: "h4 col-2 col-form-label"%>
        <%= f.text_area :content, class: "col-10 form-control" %>
      </div>
      <br>

      <%= f.submit "Add Note", class: "btn btn-primary", data: { disable_with: false } %>

    <% end %>

  </div>
</div>

app/views/games/update.html.erb
<h1>Games#update</h1>
<p>Find me in app/views/games/update.html.erb</p>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">GAME TRACKER</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if signed_in? %>
        <li class="nav-item active">
          <%= link_to "My Library", user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Add Game", new_game_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameLibrary</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script>
        $('.modal').on('hidden.bs.modal', function(e)
       {
           $(this).removeData();
       }) ;
    </script>
  </head>

  <body>
    <%= render 'layouts/nav' %>

    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <% if notice.present? %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/library/index.html.erb
<div class="col-10 offset-1 text-center">
  <br>
  <h1 >WELCOME TO GAME TRACKER!</h1>
  <% if signed_in? %>
    Hello, <%= current_user.username %>  
  <% else %>
    <p>Please sign up or log in!</p>
  <% end %>
</div>

app/views/screenshots/create.html.erb
<h1>Screenshots#create</h1>
<p>Find me in app/views/screenshots/create.html.erb</p>

app/views/screenshots/index.html.erb
<% @screenshots.each do |pic| %>
<%= pic %>

<% end %>

app/views/screenshots/show.html.erb
<br>
<div class="col-10 offset-1">
  <span id="the-pic"><%= image_tag @screenshot.picture.url, class: "img-fluid"%></span>
  <p class="pic-caption"><%= @screenshot.caption %></p>
  <br>
  <%= link_to "Back", game_path(@screenshot.game), class:'btn btn-warning col-2' %>
  <%= link_to "Delete Image", game_screenshot_path(@screenshot.game, @screenshot), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger col-2' %>
  <button class="btn btn-info col-2" id="js-next" data-pic="<%= @screenshot.id %>" data-game="<%= @screenshot.game.id %>">Next...</button>

</div>
<br>

app/views/users/_game.html.erb
<div class="row">
  <div class="col-12">
    <h1 class= "game-title text-center"><%= game.title.upcase %></h1>
  </div>
</div>
<br>
<div class="row">
  <div class="col-6">
    <%= image_tag game.screenshots.first.picture.url, class: "img-fluid rounded" %>
  </div>
  <div class="col-6">
    <p><%= game.description %></p>
  </div>
</div>
<br>
<div class="col-12 text-center">
  <%= link_to "See More", game_path(game), class: "btn btn-primary" %>
</div>

app/views/users/show.html.erb
<div class="col-10 offset-1 text-center">
  <h1>Hello, <%= @user.username %>!</h1>

  <% if @user.games.empty? %>
    <h4>You have no games :(</h4> <br>
    <h5><%= link_to "Click Here to Add a Game",  new_game_path %></h5>
  <% else %>
    <%= link_to "Add More Games", new_game_path, class: "btn btn-outline-warning btn-sm col-3" %>
    <%= link_to "See Completed Games", "/completed_games", class: "btn btn-outline-success btn-sm col-3" %>
    <h4>Your Games:</h4>
</div>
    <% @user.games.each do |game| %>
      <% if game.completed %>
        <div class="game-box-complete col-10 offset-1">
          <%= render partial: "users/game", locals: {game: game} %>
        </div>
      <% else %>
        <div class="game-box-uncomplete col-10 offset-1">
          <%= render partial: "users/game", locals: {game: game} %>
        </div>
      <% end %>
    <% end %>
  <% end %>

<br>

<div class="container game-box text-center" id="screenshot-box" data-user="<%= @user.id %>">
  <!-- render partial: "games/screenshots", locals: {screenshots: @user.screenshots} -->
</div>

app/views/users/user_completed.html.erb
<div class="col-10 offset-1 text-center">
  <h1>Your Completed Games:</h1>
</div>
  <% @games.each do |game| %>
    <% unless game.nil? %>
      <div class="game-box-complete col-10 offset-1">
        <%= render partial: "users/game", locals: {game: game} %>
      </div>
    <% end %>
  <% end %>